### ISSUE TITLE
fftw3-mpi.h - fatal error

### ISSUE THREAD

**Issue by etpalmer63** [AMReX-FHD/FHDeX#42]
I'm having an issue with `fftw3-mpi.h`. When doing make I get an error:

![image](https://user-images.githubusercontent.com/24531086/122502717-2d45fb00-cfc5-11eb-806d-1101c62a2fdb.png)

On my local machine, I "fixed" this by installing the `libfftw3-mpi-dev` packages but afterwords it still wouldn't make an executable. Then I tried to uninstall and get back and then nothing worked.

To confirm, I just tried on Kong and got the same `fftw3-mpi.h` error. Before I "fix" this too, I thought it would be a good idea to ask.

Am I doing something weird or is this a thing? Thanks.

**Comment by ajnonaka** [comment]
Try ‘make realclean’ then ‘make’.  I’ll try on kong myself once I get in gear for the day.

**Comment by etpalmer63** [comment]
You fixed it!

The `make realclean` then `make` got my local machine back to the `fftw2-mpi.h` error. Then I installed the package `libfftw3-mpi-dev` and the executables compile now.
